GET  http://localhost:5000/users
Authorization: Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsIm5hbWUiOiJBZnJ6bCIsImVtYWlsIjoiYWZyemxAZ21haWwuY29tIiwiaWF0IjoxNjczODQxMjA0LCJleHAiOjE2NzM4NDEyMjR9.-zBieJJOo-qlqe9QPe6MX-bPVZAUwfOnYALO8m-EiGw


###
POST   http://localhost:5000/users
Content-Type: application/json

{
    "name": "Afrzl",
    "email": "afrzl@gmail.com",
    "password": "12345",
    "confPassword": "12345"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "afrzl@gmail.com",
    "password": "12345"
}

###
GET http://localhost:5000/token

### 
DELETE http://localhost:5000/logout